AthleteApp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path('athletes/', include('athlete.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('athlete.urls'))
]

athlete/urls.py
from django.urls import path
from .views import AthleteListView
from . import views

urlpatterns = [
    path('', AthleteListView.as_view(), name='Home'),
    path('athletes/', views.athletes, name='Athletes'),
    path('athlete/', views.athlete_view, name='Athlete'),
]

athlete/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date

# Create your models here.
class athlete(models.Model):
    AthleteName = models.CharField(max_length=200)
    DoB = models.DateField('date of birth',null = True, blank=True)
    email = models.EmailField('email', null = True, blank=True)
    guardian = models.ManyToManyField(User)

    def __str__(self):
        return self.AthleteName

class AssessmentEvent(models.Model):
    AssessmentDate = models.DateField(default = date.today)
    Location = models.TextField(default = 'Hithercroft')
    AvHeightJump = models.FloatField(default = 0)
    AvBroadJump = models.FloatField(default = 0)
    AvGripStrength = models.FloatField(default = 0)
    AvSprint = models.FloatField(default = 0)
    AvAgilityBox = models.FloatField(default = 0)
    AvFiveFromFiveTime = models.FloatField(default = 0)
    AvFiveFromFiveBalls = models.FloatField(default = 0)
    AvHitSpeed = models.FloatField(default = 0)
    AvPushSpeed = models.FloatField(default = 0)
    AvIRYY1 = models.FloatField(default = 0)
    Comments = models.TextField(default = 'None')

    def __str__(self):
        return '%s %s' % (self.Location, str(self.AssessmentDate))

    

class assessment(models.Model):
    
    HeightJump = models.FloatField(default = 0)
    BroadJump = models.FloatField(default = 0)
    GripStrength = models.FloatField(default = 0)
    Sprint = models.FloatField(default = 0)
    AgilityBox = models.FloatField(default = 0)
    FiveFromFiveTime = models.FloatField(default = 0)
    FiveFromFiveBalls = models.FloatField(default = 0)
    HitSpeed = models.FloatField(default = 0)
    PushSpeed = models.FloatField(default = 0)
    IRYY1 = models.FloatField(default = 0)
    IncludeInAverages = models.BooleanField(default = True)
    Comments = models.TextField()
    Athlete = models.ForeignKey(athlete, on_delete=models.CASCADE)
    AssessmentEvent_FK = models.ForeignKey(AssessmentEvent, on_delete = models.CASCADE)

    def __str__(self):
        return '%s %s' % (self.Athlete.AthleteName, str(self.AssessmentEvent_FK.AssessmentDate))

athlete/forms.py
from django import forms

class UserUpdateForm(forms.ModelForm)
    class Meta:
        model = User
        fields = ['username','email']
        

athlete/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.http import HttpResponse
from django.db.models import Avg

from .models import athlete, assessment


def index(request):
    num_athletes = 2
    context = {'num_athletes':num_athletes,}
    
    return render(request, 'index.html',context = context)

def athletes(request):

    return HttpResponse('List of Athletes')

def athlete_view(request):

    athlete_data = athlete.objects.filter(guardian = request.user)
    average_data = assessment.objects.filter(IncludeInAverages = True).aggregate(Avg('HeightJump'))
    context = {'athlete_data':athlete_data,
        'average_data':average_data}
    return render(request,'athlete.html',context)


class AthleteListView(ListView):
    model = athlete
    template_name='athletes.html'
    context_object_name = 'athletes'

athlete/templates/athlete/athlete.html
{% extends "base_generic.html" %}

{% block content %}
  {%for specificathlete in athlete_data %}
  <h1>Athlete Details</h1>
  <ul>
  {{ specificathlete.email }}
  {{ specificathlete.AthleteName }}
  {{ specificathlete.DoB }}
  </ul>
        <ul>
        {{ average_data  }}

        {% for detail in specificathlete.assessment_set.all %}
            <li>Detail {{ detail.AssessmentDate }}</li>
            <li>Height Jump {{ detail.HeightJump }} cm</li>
            <li>Broad Jump {{ detail.BroadJump }} cm</li>
            <li>Grip Stregth {{ detail.GripStrength }} kg</li>
            <li>16m Sprint {{ detail.Sprint }} secs</li>
            <li>Agility Box {{ detail.AgilityBox }} secs</li>
            <li>5 From 5 {{ detail.FiveFromFiveTime }} secs</li>
            <li>for {{ detail.FiveFromFiveBalls }} balls</li>
            <li>Hit Speed {{ detail.HitSpeed }} m/s</li>
            <li>Push Speed {{ detail.PushSpeed }} m/s</li>
            <li>Yo Yo test {{ detail.IRYY1 }} </li>
            <li> Comments {{ detail.comments }} </li>

            <li> Assessment location {{ detail.AssessmentEvent_set.Location }}</li>
        {% endfor %}
        </ul>
  {% endfor %}  
{% endblock %}

athlete/templates/athlete/athletes.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Athletes</h1>
  <p>List of all athletes</em>!</p>
  <h2>Dynamic content</h2>
  <p>The app has the following record counts:</p>
  <ul>
    <li><strong>Athletes:</strong> {{ num_books }}</li>
    <li><strong>Teams:</strong> {{ num_instances }}</li>
    <li><strong>coaches:</strong> {{ num_instances_available }}</li>
    <li><strong>fixtures:</strong> {{ num_authors }}</li>
  </ul>
{% endblock %}

athlete/templates/athlete/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Athletes</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'Home' %}">Home</a></li>
          <li><a href="">All Athletes</a></li>
          <li><a href="">All Coaches</a></li>
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

athlete/templates/athlete/index.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Athletes</h1>
  <p>Welcome to Athletes a web app for Wallingfordf Wildcats</em>!</p>
  <h2>Dynamic content</h2>
  <p>The app has the following record counts:</p>
  <ul>
    <li><strong>Athletes:</strong> {{ num_books }}</li>
    <li><strong>Teams:</strong> {{ num_instances }}</li>
    <li><strong>coaches:</strong> {{ num_instances_available }}</li>
    <li><strong>fixtures:</strong> {{ num_authors }}</li>
  </ul>
{% endblock %}

athlete/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Athletes</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="">All Athletes</a></li>
          <li><a href="">All Coaches</a></li>
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>